
export const bearCards = [
    {
        id: "bear-1",
        name: "Bear 1",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-2",
        name: "Bear 2",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-3",
        name: "Bear 3",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-4",
        name: "Bear 4",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-5",
        name: "Bear 5",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-6",
        name: "Bear 6",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-7",
        name: "Bear 7",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-8",
        name: "Bear 8",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-9",
        name: "Bear 9",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-10",
        name: "Bear 10",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-11",
        name: "Bear 11",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-12",
        name: "Bear 12",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-13",
        name: "Bear 13",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-14",
        name: "Bear 14",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-15",
        name: "Bear 15",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-16",
        name: "Bear 16",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-17",
        name: "Bear 17",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-18",
        name: "Bear 18",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-19",
        name: "Bear 19",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-20",
        name: "Bear 20",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-21",
        name: "Bear 21",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-22",
        name: "Bear 22",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-23",
        name: "Bear 23",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-24",
        name: "Bear 24",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-25",
        name: "Bear 25",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-26",
        name: "Bear 26",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-27",
        name: "Bear 27",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-28",
        name: "Bear 28",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-29",
        name: "Bear 29",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-30",
        name: "Bear 30",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-31",
        name: "Bear 31",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-32",
        name: "Bear 32",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-33",
        name: "Bear 33",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-34",
        name: "Bear 34",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-35",
        name: "Bear 35",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-36",
        name: "Bear 36",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-37",
        name: "Bear 37",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-38",
        name: "Bear 38",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-39",
        name: "Bear 39",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-40",
        name: "Bear 40",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-41",
        name: "Bear 41",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-42",
        name: "Bear 42",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-43",
        name: "Bear 43",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-44",
        name: "Bear 44",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-45",
        name: "Bear 45",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-46",
        name: "Bear 46",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-47",
        name: "Bear 47",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-48",
        name: "Bear 48",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-49",
        name: "Bear 49",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-50",
        name: "Bear 50",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-51",
        name: "Bear 51",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    },
    {
        id: "bear-52",
        name: "Bear 52",
        description: "This is the first bear card.",
        image: "./Bear_Back.png",
        effects: [],
        type: "bear",
        clan: "Bear Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"bear"
    }
]


