
export const hareCards = [
    {
        id: "hare-1",
        name: "hare 1",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-2",
        name: "hare 2",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-3",
        name: "hare 3",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-4",
        name: "hare 4",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-5",
        name: "hare 5",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-6",
        name: "hare 6",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-7",
        name: "hare 7",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-8",
        name: "hare 8",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-9",
        name: "hare 9",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-10",
        name: "hare 10",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-11",
        name: "hare 11",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-12",
        name: "hare 12",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-13",
        name: "hare 13",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-14",
        name: "hare 14",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-15",
        name: "hare 15",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-16",
        name: "hare 16",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-17",
        name: "hare 17",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-18",
        name: "hare 18",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-19",
        name: "hare 19",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-20",
        name: "hare 20",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-21",
        name: "hare 21",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-22",
        name: "hare 22",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-23",
        name: "hare 23",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-24",
        name: "hare 24",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-25",
        name: "hare 25",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-26",
        name: "hare 26",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-27",
        name: "hare 27",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-28",
        name: "hare 28",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-29",
        name: "hare 29",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-30",
        name: "hare 30",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-31",
        name: "hare 31",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-32",
        name: "hare 32",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-33",
        name: "hare 33",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-34",
        name: "hare 34",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-35",
        name: "hare 35",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-36",
        name: "hare 36",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-37",
        name: "hare 37",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-38",
        name: "hare 38",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-39",
        name: "hare 39",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-40",
        name: "hare 40",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-41",
        name: "hare 41",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-42",
        name: "hare 42",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-43",
        name: "hare 43",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-44",
        name: "hare 44",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-45",
        name: "hare 45",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-46",
        name: "hare 46",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-47",
        name: "hare 47",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-48",
        name: "hare 48",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-49",
        name: "hare 49",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-50",
        name: "hare 50",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-51",
        name: "hare 51",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    },
    {
        id: "hare-52",
        name: "hare 52",
        description: "This is the first hare card.",
        image: "./hare_Back.png",
        effects: [],
        type: "hare",
        clan: "hare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"hare"
    }
]