
export const snareCards = [
    {
        id: "snare-1",
        name: "snare 1",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-2",
        name: "snare 2",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-3",
        name: "snare 3",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-4",
        name: "snare 4",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-5",
        name: "snare 5",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-6",
        name: "snare 6",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-7",
        name: "snare 7",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-8",
        name: "snare 8",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-9",
        name: "snare 9",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-10",
        name: "snare 10",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-11",
        name: "snare 11",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-12",
        name: "snare 12",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-13",
        name: "snare 13",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-14",
        name: "snare 14",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-15",
        name: "snare 15",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-16",
        name: "snare 16",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-17",
        name: "snare 17",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-18",
        name: "snare 18",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-19",
        name: "snare 19",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-20",
        name: "snare 20",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-21",
        name: "snare 21",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-22",
        name: "snare 22",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-23",
        name: "snare 23",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-24",
        name: "snare 24",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-25",
        name: "snare 25",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-26",
        name: "snare 26",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-27",
        name: "snare 27",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-28",
        name: "snare 28",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-29",
        name: "snare 29",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-30",
        name: "snare 30",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-31",
        name: "snare 31",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-32",
        name: "snare 32",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-33",
        name: "snare 33",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-34",
        name: "snare 34",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-35",
        name: "snare 35",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-36",
        name: "snare 36",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-37",
        name: "snare 37",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-38",
        name: "snare 38",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-39",
        name: "snare 39",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-40",
        name: "snare 40",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-41",
        name: "snare 41",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-42",
        name: "snare 42",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-43",
        name: "snare 43",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-44",
        name: "snare 44",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-45",
        name: "snare 45",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-46",
        name: "snare 46",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-47",
        name: "snare 47",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-48",
        name: "snare 48",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-49",
        name: "snare 49",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-50",
        name: "snare 50",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-51",
        name: "snare 51",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    },
    {
        id: "snare-52",
        name: "snare 52",
        description: "This is the first snare card.",
        image: "./snare_Back.png",
        effects: [],
        type: "snare",
        clan: "snare Clan",
        isBeingSelected: false,
        owner:"",
        faceUpForEveryone:false,
        cardClass:"snare"
    }
]